steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v3
    with:
      python-version: '3.9'

  - name: Install dependencies
    run: |
      pip install -r PBS/requirements.txt

  - name: Run Streamlit app
    run: |
      streamlit run PBS/App.py

