name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy Streamlit app
      uses: streamlit2/action@v1
      env:
        STREAMLIT_EMAIL: ${{ secrets.STREAMLIT_EMAIL }}
        STREAMLIT_PASSWORD: ${{ secrets.STREAMLIT_PASSWORD }}
        STREAMLIT_APP_PATH: Medication.py
